Repository FRONT-END-BOOTCAMP-PLUS-4/Team_06_WayGo, pull requests merged in 2025-04, with the labels that each got.

#17 [feat] application > 백엔드 application 구조 설정
  application/usecases/budget/BudgetListUsecase.ts
  application/usecases/budget/dto/BudgetListDto.ts
  application/usecases/comments/CommentListUsecase.ts
  application/usecases/comments/CreateCommentUsecase.ts
  application/usecases/comments/DeleteCommentUsecase.ts
  application/usecases/comments/EditCommentUsecase.ts
  application/usecases/comments/dto/CommentListDto.ts
  application/usecases/comments/dto/CreatecommentDto.ts
  application/usecases/comments/dto/DeleteCommentDto.ts
  application/usecases/comments/dto/EditCommentDto.ts
  application/usecases/comments/dto/RespondCommentDto.ts
  application/usecases/duration/DurationListUsecase.ts
  application/usecases/duration/dto/DurationListDto.ts
  application/usecases/location/LocationListUsecase.ts
  application/usecases/location/dto/LocationListDto.ts
  application/usecases/plans/CreatePlanUsecase.ts
  application/usecases/plans/DeletePlanUsecase.ts
  application/usecases/plans/EditPlanUsecase.ts
  application/usecases/plans/PlanListUsecase.ts
  application/usecases/plans/dto/CreatePlanDto.ts
  application/usecases/plans/dto/DeletePlanDto.ts
  application/usecases/plans/dto/EditPlanDto.ts
  application/usecases/plans/dto/PlanListUsecase.ts
  application/usecases/plans/dto/RespondPlanDto.ts
  application/usecases/season/SeasonListUsecase.ts
  application/usecases/season/dto/SeasonListDto.ts
  application/usecases/users/CreateUserUsecase.ts
  application/usecases/users/EdituserUsecase.ts
  application/usecases/users/UserUsecase.ts
  application/usecases/users/dto/CreateUserDto.ts
  application/usecases/users/dto/EditUserDto.ts
  application/usecases/users/dto/UserDto.ts
Labels: enhancement, P1

#23 [chore] ESLint 및 Prettier 설정
  .vscode/settings.json
  eslint.config.mjs
  package-lock.json
  package.json
  prettier.config.js
Labels: enhancement, P2

#29 [design] 기본 레이아웃 및 기본 폰트 스타일, 사이즈 지정
  app/favicon.ico
  app/globals.css
  app/globals.scss
  app/layout.tsx
  app/page.module.css
  app/page.module.scss
  app/page.tsx
  app/styles/definition.scss
  public/file.svg
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Regular.woff2
  public/globe.svg
  public/logos/favicon.png
  public/next.svg
  public/vercel.svg
  public/window.svg
  tsconfig.json
Labels: enhancement, P1

#40 [feat] 셀렉트기본/포커스 컴포넌트
  app/components/selectBasic/selectBasic.module.scss
  app/components/selectBasic/selectBasic.tsx
  app/globals.scss
Labels: enhancement, P1

#41 [feat] 인풋 컴포넌트 구현(일반, 비밀번호, 검색)
  app/(public)/page.tsx
  app/components/button/Button.tsx
  app/components/button/button.module.scss
  app/components/checkInput/CheckInput.tsx
  app/components/inputError/InputError.tsx
  app/components/inputError/inputError.module.scss
  app/components/pwInput/PwInput.tsx
  app/components/searchInput/SearchInput.tsx
  app/components/textInput/TextInput.tsx
  app/components/textInput/textInput.module.scss
  app/globals.scss
  prettier.config.js
  public/logos/logo-slogan.svg
Labels: enhancement, P1

#48 [enhance] 셀렉트 박스 컴포넌트 수정
  app/(public)/page.tsx
  app/components/selectBasic/selectBasic.module.scss
  app/components/selectBasic/selectBasic.tsx
Labels: enhancement, P3

#53 [feat] 메인 페이지, 검색결과 페이지 퍼블리싱 PlanCardList scroll props 추가
  app/(public)/main.module.scss
  app/(public)/page.tsx
  app/(public)/plans/page.tsx
  app/(public)/plans/plans.module.scss
  app/components/planCard/PlanCard.tsx
  app/components/planCard/planCard.module.scss
  app/components/planCardList/PlanCardList.tsx
  app/components/planCardList/planCardList.module.scss
  app/components/selectBasic/selectBasic.module.scss
Labels: enhancement, P1

#51 [feat] 계획 작성/수정 페이지 퍼블리싱
  app/(private)/layout.tsx
  app/(private)/plans/create/components/FileBox.tsx
  app/(private)/plans/create/components/fileBox.module.scss
  app/(private)/plans/create/create.module.scss
  app/(private)/plans/create/page.tsx
  app/components/rootFooter/rootFooter.module.scss
  app/components/rootHeader/rootHeader.module.scss
  app/components/selectBasic/selectBasic.tsx
  app/components/textArea/TextArea.tsx
  app/components/textArea/textArea.module.scss
  app/components/withAuth.tsx
  app/globals.scss
  app/layout.tsx
  package-lock.json
  package.json
Labels: enhancement, P1

#56 [feat] 작성 완료 페이지, error 페이지 퍼블리싱
  app/(private)/plans/complete/complete.module.scss
  app/(private)/plans/complete/page.tsx
  app/(public)/page.tsx
  app/(public)/plans/page.tsx
  app/globals.scss
  app/not-found.module.scss
  app/not-found.tsx
Labels: enhancement

#57 [feat] 마이 프로필 페이지 추가
  app/(private)/my-profile/components/commentedCardList/CommentedCardList.tsx
  app/(private)/my-profile/components/commentedCardList/commentedCardList.module.scss
  app/(private)/my-profile/components/commentedPlanCard/CommentedPlanCard.tsx
  app/(private)/my-profile/components/commentedPlanCard/commentedPlanCard.module.scss
  app/(private)/my-profile/components/userInfoCard/UserInfoCard.tsx
  app/(private)/my-profile/components/userInfoCard/userInfoCard.module.scss
  app/(private)/my-profile/myProfile.module.scss
  app/(private)/my-profile/page.tsx
  app/(private)/plans/create/components/FileBox.tsx
  app/(private)/plans/create/components/fileBox.module.scss
  app/(public)/main.module.scss
  app/(public)/plans/plans.module.scss
  app/components/pagination/pagination.module.scss
  app/components/planCard/planCard.module.scss
  app/components/rootFooter/rootFooter.module.scss
  app/components/rootHeader/rootHeader.module.scss
Labels: enhancement, P1

#55 [feat] auth 페이지 > 로그인 / 회원가입 페이지 추가
  app/(public)/(auth)/layout.module.scss
  app/(public)/(auth)/layout.tsx
  app/(public)/(auth)/login/login.module.scss
  app/(public)/(auth)/login/page.tsx
  app/(public)/(auth)/signup/page.tsx
  app/(public)/(auth)/signup/signup.module.scss
  app/(public)/page.module.scss
  app/components/checkInput/CheckInput.tsx
  app/components/pwInput/PwInput.tsx
  public/images/auth-cover.jpg
Labels: enhancement

#61 [enhance] 공통 헤더 컴포넌트 수정
  app/components/profileDropdown/ProfileDropdown.tsx
  app/components/profileDropdown/profileDropdown.module.scss
  app/components/rootHeader/RootHeader.tsx
  app/components/rootHeader/rootHeader.module.scss
  app/components/withAuth.tsx
Labels: enhancement, P2

#64 [feat] my-profile edit page 퍼블리싱 반영
  app/(private)/my-profile/components/userInfoCard/UserInfoCard.tsx
  app/(private)/my-profile/edit/edit.module.scss
  app/(private)/my-profile/edit/page.tsx
Labels: enhancement

#72 [feat] 카테고리 관련 DTO 설정
  application/usecases/budget/dto/BudgetListDto.ts
  application/usecases/duration/dto/DurationListDto.ts
  application/usecases/location/dto/LocationListDto.ts
  application/usecases/season/dto/SeasonListDto.ts
Labels: enhancement

#71 [feat] 여행 계획 목록, 상세 DTO 구현
  application/usecases/plans/dto/PlanCardDto.ts
  application/usecases/plans/dto/PlanDetailDto.ts
  application/usecases/plans/dto/PlanListDto.ts
Labels: enhancement

#81 [feat] app/components/dropdown > 드롭다운 수정
  app/(public)/plans/[id]/components/comments/commentCard/CommentCard.tsx
  app/components/dropdown/Dropdown.tsx
  app/components/dropdown/dropdown.module.scss
  app/components/profileDropdown/ProfileDropdown.tsx
  app/components/rootHeader/RootHeader.tsx
  app/member/plans/[id]/components/comments/commentCard/CommentCard.tsx
  application/usecases/comments/DeleteCommentUsecase.ts
  application/usecases/comments/EditCommentUsecase.ts
  hooks/useOutsideClick.ts
  infra/repositories/supabase/SbCommentRepository.ts
Labels: enhancement, P2

#85 [feat] 여행 계획 이미지 Entity, Repository 추가
  domain/entities/PlanImg.ts
  domain/repositories/PlanImgRepository.ts
Labels: enhancement, P1

#102 Feat/101 create user auth/ho
  app/api/auth/login/route.ts
  app/api/auth/signup/route.ts
  app/api/login/route.ts
  app/api/signup/route.ts
  app/api/users/[id]/route.ts
  app/api/users/route.ts
  app/member/layout.tsx
  application/usecases/auth/LoginUsecase.ts
  application/usecases/auth/SignUpUsecase.ts
  application/usecases/auth/dto/LoggedInDto.ts
  application/usecases/auth/dto/LoginDto.ts
  application/usecases/auth/dto/SignUpDto.ts
  application/usecases/auth/dto/SignedUpDto.ts
  domain/entities/User.ts
  domain/repositories/UserRepository.ts
  infra/repositories/supabase/SbUserRepository.ts
  middleware.ts
  package-lock.json
  package.json
  stores/authStore.ts
Labels: enhancement

#120 [feat] 회원 인증 기능 추가
  app/(public)/(auth)/layout.tsx
  app/(public)/(auth)/login/page.tsx
  app/(public)/(auth)/signup/page.tsx
  app/(public)/(auth)/signup/signup.module.scss
  app/api/auth/duplicate/[type]/route.ts
  app/api/auth/login/route.ts
  app/api/auth/route.ts
  app/api/auth/signup/route.ts
  app/api/users/route.ts
  app/components/checkInput/CheckInput.tsx
  app/components/inputError/inputError.module.scss
  app/components/pwInput/PwInput.tsx
  app/components/rootHeader/RootHeader.tsx
  app/components/toast/Toast.tsx
  app/components/toast/toast.module.scss
  app/components/withAuth.tsx
  app/layout.tsx
  application/usecases/auth/LoginUsecase.ts
  application/usecases/auth/SignUpUsecase.ts
  application/usecases/auth/dto/SignUpDto.ts
  domain/entities/User.ts
  domain/repositories/UserRepository.ts
  hooks/useOutsideClick.ts
  infra/repositories/supabase/SbUserRepository.ts
  middleware.ts
  public/images/auth-cover.jpg
  public/images/auth-cover1.jpg
  public/images/auth-cover2.jpg
  public/images/auth-cover3.jpg
  public/images/auth-cover4.jpg
  stores/authStore.ts
  utils/jwt.ts
Labels: enhancement

#122 [feat] 회원/비회원 라우팅 수정
  app/(public)/layout.tsx
  app/components/rootHeader/RootHeader.tsx
  app/member/layout.tsx
Labels: enhancement, P3

#125 [fix] 회원 인증 버그 수정 및 toast css 수정
  app/(public)/(auth)/login/page.tsx
  app/(public)/(auth)/signup/page.tsx
  app/components/GlobalToast.tsx
  app/components/rootHeader/RootHeader.tsx
  app/components/toast/Toast.tsx
  app/components/toast/toast.module.scss
  app/components/withAuth.tsx
  app/layout.tsx
  stores/toastStore.ts
Labels: enhancement

#128 [feat] 여행 계획 상세 페이지 기능 구현
  app/(public)/plans/[id]/components/travelPlanOverview/TravelPlanOverview.tsx
  app/(public)/plans/[id]/components/travelPlanOverview/overviewCarousel/OverviewCarousel.tsx
  app/(public)/plans/[id]/components/travelPlanOverview/overviewCarousel/overviewCarousel.module.scss
  app/(public)/plans/[id]/components/tripGuide/TripGuide.tsx
  app/(public)/plans/[id]/components/tripGuide/tripGuide.module.scss
  app/(public)/plans/[id]/detail.module.scss
  app/(public)/plans/[id]/page.tsx
  app/api/plans/[id]/route.ts
  app/member/plans/[id]/components/comments/commentCard/commentCard.module.scss
  app/member/plans/[id]/components/travelPlanOverview/TravelPlanOverview.tsx
  app/member/plans/[id]/components/travelPlanOverview/overviewCarousel/OverviewCarousel.tsx
  app/member/plans/[id]/components/travelPlanOverview/overviewCarousel/overviewCarousel.module.scss
  app/member/plans/[id]/components/tripGuide/TripGuide.tsx
  app/member/plans/[id]/components/tripGuide/tripGuide.module.scss
  app/member/plans/[id]/detail.module.scss
  app/member/plans/[id]/page.tsx
  application/usecases/plans/PlanDetailUsecase.ts
  domain/entities/Plan.ts
  domain/repositories/PlanRepository.ts
  infra/repositories/supabase/SbPlanRepository.ts
  package-lock.json
  package.json
Labels: enhancement, P1

#118 [feat] 여행 계획 검색 기능 추가
  app/(public)/plans/[id]/components/comments/Comments.tsx
  app/(public)/plans/page.tsx
  app/(public)/plans/plans.module.scss
  app/api/plans/popular/route.ts
  app/api/plans/route.ts
  app/api/plans/season/route.ts
  app/components/pagination/Pagination.tsx
  app/components/planCard/PlanCard.tsx
  app/components/planCard/planCard.module.scss
  app/components/planCardList/PlanCardList.tsx
  app/components/searchInput/SearchInput.tsx
  app/components/selectBasic/selectBasic.tsx
  app/components/textInput/TextInput.tsx
  app/member/plans/page.tsx
  app/member/plans/plans.module.scss
  application/usecases/plans/PlanListUsecase.ts
  application/usecases/plans/dto/PlanCardDto.ts
  application/usecases/plans/dto/PlanFilterDto.ts
  application/usecases/plans/dto/PlanListDto.ts
  domain/entities/Plan.ts
  domain/repositories/PlanRepository.ts
  infra/repositories/supabase/SbPlanImgRepository.ts
  infra/repositories/supabase/SbPlanRepository.ts
Labels: enhancement

#139 [design] 부자연스러운 UI 수정
  app/(public)/plans/[id]/components/comments/comments.module.scss
  app/(public)/plans/page.tsx
  app/(public)/plans/plans.module.scss
  app/components/rootHeader/RootHeader.tsx
  app/components/rootHeader/rootHeader.module.scss
  app/components/selectBasic/selectBasic.module.scss
  app/components/textInput/textInput.module.scss
  app/member/components/userInfoCard/UserInfoCard.tsx
  app/member/components/userInfoCard/userInfoCard.module.scss
  app/member/plans/[id]/components/comments/comments.module.scss
  app/member/plans/page.tsx
  app/member/plans/plans.module.scss
Labels: enhancement, P3

#137 [feat] 메인 페이지 인기 여행 계획 영역 구현
  app/api/plans/popular/route.ts
  app/components/planCardList/PlanCardList.tsx
  app/components/rootFooter/RootFooter.tsx
  app/components/rootHeader/RootHeader.tsx
  app/components/rootHeader/rootHeader.module.scss
  app/member/member.module.scss
  app/page.tsx
  application/usecases/plans/PlanListUsecase.ts
  application/usecases/plans/dto/PlanCardDto.ts
  domain/entities/Plan.ts
  infra/repositories/supabase/SbPlanRepository.ts
Labels: enhancement, P1

#141 [fix] 토큰 만료 처리
  app/(public)/(auth)/login/page.tsx
  app/api/auth/login/route.ts
  app/components/authToken/withAuth.tsx
  app/components/button/button.module.scss
  app/components/loadingArea/LoadingArea.tsx
  app/components/loadingArea/loadingArea.module.scss
  app/components/planCardList/PlanCardList.tsx
  app/components/pwInput/PwInput.tsx
  app/components/rootHeader/RootHeader.tsx
  app/components/rootHeader/rootHeader.module.scss
  app/components/textArea/textArea.module.scss
  app/components/textInput/TextInput.tsx
  app/components/toast/toast.module.scss
  app/layout.tsx
  app/member/components/commentedCardList/CommentedCardList.tsx
  app/member/components/commentedCardList/commentedCardList.module.scss
  app/member/page.tsx
  app/member/plans/[id]/components/comments/commentCard/commentCard.module.scss
  app/member/plans/[id]/components/comments/comments.module.scss
  app/member/plans/[id]/components/travelPlanOverview/overviewCarousel/overviewCarousel.module.scss
  app/member/plans/[id]/components/travelPlanOverview/travelPlanOverview.module.scss
  app/member/plans/[id]/components/tripGuide/tripGuide.module.scss
  app/member/plans/[id]/detail.module.scss
  middleware.ts
  stores/authStore.ts
  test.tsx
  utils/apiClient.ts
  utils/authUtils.ts
Labels: enhancement, P2
